[book]
authors = ["Anton Arhipov"]
language = "en"
#multilingual = false
src = "src"
title = "The Sonic Byte"
description = "A guide to programming dark electronic music with Sonic Pi"

[build]
build-dir = "book"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/antonarhipov/sonic-byte"
edit-url-template = "https://github.com/antonarhipov/sonic-byte/sonic-byte-tutorial/edit/main/{path}"
additional-js = ["src/pdf-toc.js"]
additional-css = ["src/pdf-toc.css"]

[output.html.fold]
enable = true
level = 1

[output.pdf]
generate-document-outline = true

